Iter5
WPGe/go-yandex-advanced pull request #5
Opened 2023-10-05 14:25 UTC by WPGe

2023-10-08 14:17 UTC, vovean requested changes

2023-10-08 14:17 UTC, vovean commented on cmd/agent/flag.go
> +	if cfg.Address != "" {
получается, переменные окружения имеют приоритет перед флагами? Может стоит использовать только один источник конфигурации? Если при запуске программы будут перемешиваться откуда какие параметры мы передаем, то пользователю будет легко запутаться.

Я бы предпочел переменные окружения, потому что 1) их использование соответствует 12 Factor Apps 2) переменные окружения можно прям как флаги задавать перед запуском каждой команды и они буду действовать только на этот запуск команды, а не на все окружение (принятый ответ вот здесь показывает, как это сделать: https://unix.stackexchange.com/questions/56444/how-do-i-set-an-environment-variable-on-the-command-line-and-have-it-appear-in-c)

2023-10-08 14:17 UTC, vovean commented on cmd/agent/main.go
> +	select {}
хмм, остаток от какой-то нереализованной идеи? Может стоит удалить

2023-10-08 14:17 UTC, vovean commented on cmd/server/flag.go
> +	if envRunAddr := os.Getenv("ADDRESS"); envRunAddr != "" {
в агенте используется структура конфига с автоматическим анмаршалингом значений из переменных окружения, а здесь ты работаешь напрямую с пакетом os. Как минимум из соображений консистентности подхода к написанию кода стоит использовать в обоих местах. К тому же подход со структурой более расширяемый

2023-10-08 14:17 UTC, vovean commented on cmd/server/main.go
> +	log.Fatal(http.ListenAndServe(flagRunAddr, r))
такое использование сервера не подразумевает graceful shutdown. Хорошей практикой является его использование. Подробнее про graceful shutdown и, в частности, о том, как его реализоваться с http.Server можно почитать здесь: https://www.rudderstack.com/blog/implementing-graceful-shutdown-in-go/

2023-10-08 14:17 UTC, vovean commented on internal/agent/metric.go
> +func MetricAgent(repo repository.MetricRepository, hookPath string, reportInterval int, pollInterval int, stopCh <-chan struct{}) {
может принимать time.Duration, а не int для параметров интервала? Потому что при использовании этой функции непонятно, в каких единицах измеряется интервал. И что, если я хочу интервал меньше секунды?

2023-10-08 14:17 UTC, vovean commented on internal/agent/metric.go
> +	return map[string]float64{
каждый раз тут будет создаваться мапа, класться в кучу (разве что гошный компилятор произведет инлайнинг этой функции) и передаваться в вызывающую функцию. Потом сборщику мусора придется подчищать эту мапу.

Можно подумать в сторону того, чтобы использовать один экземпляр мапы и каждый раз заполнять его, а перед очередным считыванием метрик очищать его. Это, возможно, несколько усложнит программу, но улучшит работу с памятью

2023-10-08 14:17 UTC, vovean commented on internal/agent/metric.go
> +	return map[string]float64{
Проверить, используется ли куча для передачи мапы (или происходит инлайнинг) можно включить вывод escape analysis в процессе компиляции: `go build -gcflags "-m -m"`

Подробнее:  https://habr.com/ru/articles/497994/

2023-10-08 14:17 UTC, vovean commented on internal/agent/metric.go
> +}
хм, странная логика...

2023-10-08 14:17 UTC, vovean commented on internal/agent/metric.go
> +}
не уверен, что эта метрика делает, но использование захардкоженного значения - точно не расширяемое решение

2023-10-08 14:17 UTC, vovean commented on internal/agent/metric.go
> +		_, err := req.Send()
было бы хорошо еще проверить response code и вывести его, если он не 2ХХ

2023-10-08 14:17 UTC, vovean commented on internal/handler/update_handler.go
> +			http.Error(w, "Некорректный формат URL", http.StatusNotFound)
может отдавать ошибки на английском языке? Как минимум на некоторых платформах могут возникнуть проблемы с отображением русского языка, как максимум, вдруг, этим проектом, однажды, будет пользоваться нерусскоговорящий пользователь

2023-10-08 14:17 UTC, vovean commented on internal/handler/update_handler.go
> +			if _, err := io.WriteString(w, fmt.Sprintf("%g", resultMetric.Value)); err != nil {
отличное применение пакета io!

2023-10-08 14:17 UTC, vovean commented on internal/repository/metric.go
> +	AddMetric(name string, metric entity.Metric)
не может ли быть тут ошибки? Например, в будущем, если будет использоваться какая-то БД, то она точно будет возвращать ошибку

2023-10-08 14:17 UTC, vovean commented on internal/repository/metric.go
> +	AddMetric(name string, metric entity.Metric)
в методах ниже - аналогично

2023-10-08 14:17 UTC, vovean commented on internal/storage/mem_storage.go
> +	mu      sync.Mutex
RWMutex? Можно делать RLock для операций чтения и Lock для записи

2023-10-08 14:17 UTC, vovean commented on internal/storage/mem_storage.go
> +	} else {
можно сделать early return и обойтись без else, уменьшив уровень вложенности кода

2023-10-15 13:07 UTC, WPGe commented on cmd/agent/main.go
> +	select {}
функция агента по условию задачи должна работать бесконечно, каждый flagPollInterval собирая метрики и каждый flagReportInterval отправляя метрики. select{} нужен, чтобы заблокировать горутину, чтобы она ждала выполнение описанных событий

2023-10-15 13:12 UTC, WPGe commented on cmd/agent/flag.go
> +	if cfg.Address != "" {
флаги и переменные окружения используются совместно, т.к. это указано в задаче для инкрементов 4 и 5 и ожидается тестами
после прочтения статьи я все равно не вижу способа оставить только один вариант, притом, что названия для флагов и переменных окружения жестко указаны в задании и тестах

2023-10-15 13:13 UTC, WPGe commented on internal/agent/metric.go
> +	return map[string]float64{
я решил в таком случае вообще избавиться от промежуточного хранения метрик в map и сразу записывать все в хранилище

2023-10-15 13:14 UTC, WPGe commented on internal/agent/metric.go
> +}
тут метрика является счетчиком, который просто увеличивается на 1 при каждом сборе метрик.
Чтобы стало понятнее, не смог придумать ничего лучше, чем вынести это в отдельную функцию increasePollIteration, в названии которой явно указано, что в ней делается

2023-10-17 12:26 UTC, WPGe commented on cmd/agent/main.go
> +	select {}
убрал лишний вызов отдельной горутины, т.к. внутри функции уже есть бесконечный цикл

2023-10-18 20:20 UTC, vovean commented on cmd/agent/flag.go
> +	if cfg.Address != "" {
согласен, из-за тестов придется так сделать

но хорошо, что статью прочитала)

2023-10-18 20:22 UTC, vovean approved these changes

2023-11-09 01:00 UTC, merged